### ISSUE TITLE
GCC 13 build failure

### ISSUE THREAD

**Issue by devrimgunduz** [okbob/pgimportdoc#5]
Hi,

pgimportdoc fails to build against GCC 13 (Fedora 38). Can you please take a look? Thanks!

```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -I/usr/pgsql-14/include -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o pgimportdoc.o pgimportdoc.c
/usr/lib64/ccache/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Xclang -no-opaque-pointers -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-deprecated-non-prototype -O2  -I/usr/pgsql-14/include -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o pgimportdoc.bc pgimportdoc.c
pgimportdoc.c:106:3: error: call to undeclared function 'simple_prompt'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                simple_prompt("Password: ", password, sizeof(password), false);
                ^
pgimportdoc.c:162:4: error: call to undeclared function 'simple_prompt'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                        simple_prompt("Password: ", password, sizeof(password), false);
                        ^
2 errors generated.
make[1]: *** [/usr/pgsql-14/lib/pgxs/src/makefiles/../../src/Makefile.global:1071: pgimportdoc.bc] Error 1
make[1]: *** Waiting for unfinished jobs....
pgimportdoc.c: In function 'pgimportdoc':
pgimportdoc.c:106:17: warning: implicit declaration of function 'simple_prompt' [-Wimplicit-function-declaration]
  106 |                 simple_prompt("Password: ", password, sizeof(password), false);
      |                 ^~~~~~~~~~~~~

```

**Comment by okbob** [comment]
Hi


so 22. 4. 2023 v 20:00 odesílatel Devrim Gündüz ***@***.***>
napsal:

> Hi,
>
> pgimportdoc fails to build against GCC 13 (Fedora 38). Can you please take
> a look? Thanks!
>
> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -I/usr/pgsql-14/include -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o pgimportdoc.o pgimportdoc.c
> /usr/lib64/ccache/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Xclang -no-opaque-pointers -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-deprecated-non-prototype -O2  -I/usr/pgsql-14/include -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o pgimportdoc.bc pgimportdoc.c
> pgimportdoc.c:106:3: error: call to undeclared function 'simple_prompt'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
>                 simple_prompt("Password: ", password, sizeof(password), false);
>                 ^
> pgimportdoc.c:162:4: error: call to undeclared function 'simple_prompt'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
>                         simple_prompt("Password: ", password, sizeof(password), false);
>                         ^
> 2 errors generated.
> make[1]: *** [/usr/pgsql-14/lib/pgxs/src/makefiles/../../src/Makefile.global:1071: pgimportdoc.bc] Error 1
> make[1]: *** Waiting for unfinished jobs....
> pgimportdoc.c: In function 'pgimportdoc':
> pgimportdoc.c:106:17: warning: implicit declaration of function 'simple_prompt' [-Wimplicit-function-declaration]
>   106 |                 simple_prompt("Password: ", password, sizeof(password), false);
>       |                 ^~~~~~~~~~~~~
>
>
>
I have Fedora 38, and I built it without any problems.

More the error message is strange

The definition is in header file common/string.h

and my source code contains:

#if PG_VERSION_NUM >= 140000

#include "common/string.h"

#endif

**Comment by okbob** [comment]
so 22. 4. 2023 v 22:20 odesílatel Pavel Stehule ***@***.***>
napsal:

> Hi
>
>
> so 22. 4. 2023 v 20:00 odesílatel Devrim Gündüz ***@***.***>
> napsal:
>
>> Hi,
>>
>> pgimportdoc fails to build against GCC 13 (Fedora 38). Can you please
>> take a look? Thanks!
>>
>> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -I/usr/pgsql-14/include -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o pgimportdoc.o pgimportdoc.c
>> /usr/lib64/ccache/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Xclang -no-opaque-pointers -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-deprecated-non-prototype -O2  -I/usr/pgsql-14/include -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o pgimportdoc.bc pgimportdoc.c
>> pgimportdoc.c:106:3: error: call to undeclared function 'simple_prompt'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
>>                 simple_prompt("Password: ", password, sizeof(password), false);
>>                 ^
>> pgimportdoc.c:162:4: error: call to undeclared function 'simple_prompt'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
>>                         simple_prompt("Password: ", password, sizeof(password), false);
>>                         ^
>> 2 errors generated.
>> make[1]: *** [/usr/pgsql-14/lib/pgxs/src/makefiles/../../src/Makefile.global:1071: pgimportdoc.bc] Error 1
>> make[1]: *** Waiting for unfinished jobs....
>> pgimportdoc.c: In function 'pgimportdoc':
>> pgimportdoc.c:106:17: warning: implicit declaration of function 'simple_prompt' [-Wimplicit-function-declaration]
>>   106 |                 simple_prompt("Password: ", password, sizeof(password), false);
>>       |                 ^~~~~~~~~~~~~
>>
>>
>>
> I have Fedora 38, and I built it without any problems.
>
> More the error message is strange
>
> The definition is in header file common/string.h
>
> and my source code contains:
>
> #if PG_VERSION_NUM >= 140000
>
> #include "common/string.h"
>
> #endif
>
>
>
Maybe you miss
https://github.com/okbob/pgimportdoc/commit/6a43a2e7d79d2cdfb2831aa9938d3aa77925aa30

**Comment by devrimgunduz** [comment]
Hi,

I don't think I' m missing anything -- except there is no release which contains that fix, right? RPMs require a tarball.

Can you please release a new version?

Thanks!

Regards, Devrim

**Comment by okbob** [comment]
sure, done

there is 0.1.4 released

**Comment by devrimgunduz** [comment]
Thanks!
